FROM python:3.10-slim

# Working directory
WORKDIR /app

# Python dependencies
COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# App code copy karo
COPY frontend/ ./frontend/
COPY .env .env

# Port expose karo
EXPOSE 8501

# Streamlit start karo
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]